---
_extends: .github

repository:
  name: js-toxcore-c
  description: Node bindings for toxcore
  topics: toxcore, javascript

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - DeepScan
          - Travis CI - Pull Request
          - code-review/reviewable
          - codecov/patch
          - codecov/project
          - security/snyk (TokTok)
