language: node_js
sudo: false

cache:
  directories:
    - $HOME/cache

node_js:
  - "0.10"
#  - "0.12"
#  - "1"
#  - "2"
#  - "3.2"
#  - "4"

addons: {apt: {packages: [yasm, g++-4.8], sources: [ubuntu-toolchain-r-test]}}

# io.js v3+ requires C++11
before_install:
  - export CXX="g++-4.8"

before_script:
  - export CACHE_DIR="$HOME/cache"
  - export CFLAGS="-I$CACHE_DIR/usr/include"
  - export LDFLAGS="-L$CACHE_DIR/usr/lib"
  - export LD_LIBRARY_PATH="$CACHE_DIR/usr/lib"
  - export PKG_CONFIG_PATH="$CACHE_DIR/usr/lib/pkgconfig"
  - tools/install-deps.sh > /dev/null
